DEFAULT_QUESTION_BLOCK_SEP = '$$'
DEFAULT_WRONG_OPTION_PREFIX = ' ' * 4
DEFAULT_CORRECT_OPTION_PREFIX = '+' + ' ' * 3
DEFAULT_TESTS_COLLECTION_NAME = 'Volorova'

DEFAULT_OUT_FILE_NAME = 'parsed.json'
